// Generated by CoffeeScript 1.4.0
var elix;

module.exports = elix = {
  configure: function(stacker, config) {
    return elix.server = new (require('./server'))(config);
  },
  edge: function(placeholder, nodes) {
    if (nodes.from["class"] === 'elix' && nodes.tree === 'up') {
      elix.server.start();
    }
    return console.log('%s:%s --> %s:%s', nodes.from["class"], nodes.from.label, nodes.to["class"], nodes.to.label);
  }
};
