// Generated by CoffeeScript 1.4.0
var elix;

module.exports = elix = {
  configure: function(stacker, config) {
    return elix.server = new (require('./server'))(config);
  },
  edge: function(placeholder, nodes) {
    if (nodes.to["class"] === 'elix') {
      return elix.server.start();
    }
  }
};
