// Generated by CoffeeScript 1.4.0
var elix;

module.exports = elix = {
  configure: function(stacker, config) {
    return elix.server = new (require('./server'))(config);
  },
  hup: function() {
    return console.log('(hup) - pending propagate into tree');
  },
  edge: function(placeholder, nodes) {
    if (nodes.from["class"] === 'elix' && nodes["class"] === 'Tree.Rootward') {
      return elix.server.start();
    }
  },
  handles: ['node', 'service'],
  matches: [],
  node: function(node) {
    return console.log('(register) %s:%s', node["class"], node.label);
  },
  service: function(node) {
    return console.log('(register) %s:%s', node["class"], node.label);
  }
};
