// Generated by CoffeeScript 1.4.0
var Protocols;

module.exports = Protocols = {
  bind: function(receive, send) {
    return receive('event:connect', function(payload) {
      return console.log(payload);
    });
  }
};
