// Generated by CoffeeScript 1.4.0
var Server;

Server = (function() {

  function Server(config) {
    this.config = config;
  }

  Server.prototype.start = function() {
    console.log('start with', this.config);
    return require('plex').start({
      mode: 'root',
      listen: {
        adaptor: 'socket.io',
        port: this.config.port
      }
    });
  };

  return Server;

})();

module.exports = Server;
